# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_schema', '0004_fieldschema_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldschema',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='field_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='field_type',
            field=models.CharField(choices=[('BOOLEAN', 'BOOLEAN'), ('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('DATE_FLOORED', 'DATE_FLOORED'), ('DURATION', 'DURATION'), ('FLOAT', 'FLOAT'), ('INT', 'INT'), ('STRING', 'STRING')], max_length=32),
        ),
    ]
