# Generated by Django 3.2.18 on 2023-04-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data_schema', '0006_auto_20220818_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='model_content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='field_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='uniqueness_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
